services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=server"
    network_mode: host

  client:
    build:
      args:
        SPRING_PROFILES_ACTIVE: "client"
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=client"
    network_mode: host

