version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "profile=server"

  client:
    build:
      args:
        SPRING_PROFILES_ACTIVE: "client"
    ports:
      - "8081:8081"
    environment:
      - "profile=client"
      - "destination=server:8080"
